### ISSUE TITLE
Add possibility to make intersection of shapes

### ISSUE THREAD

**Issue by ToniaDemchuk** [SixLabors/ImageSharp.Drawing#10]
This library has only simple difference clipping. It would be nice to have other types of clipping (intersect, union). 

As I see, you use ClippingLib under the hood and it has support for intersection.

**Comment by antonfirsov** [comment]
Makes sense, but low priority, moving to Future. Community PR-s are welcome.

**Comment by JimBobSquarePants** [comment]
On it. See #265 265
