### ISSUE TITLE
Convenience constructors for shapes

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp.Drawing#100]
Given a `PointF` arrays `contour` and `hole`, this is how a `ComplexPolygon` could be constructed today:

```C#
ComplexPolygon polygon = new ComplexPolygon(
                new Path(new LinearLineSegment(contour)),
                new Path(new LinearLineSegment(hole)));
```

It should be as easy as:
```C#
ComplexPolygon polygon = new ComplexPolygon(contour, hole);
```

We need to review the shape types and add convenience constructors based on the principle of "good defaults".

**Comment by JimBobSquarePants** [comment]
@antonfirsov I'm assuming we'd accept a `Span<PointF>` for each parameter?

**Comment by antonfirsov** [comment]
Hah, this seems to be an easy question but it isn't.

Currently the [`LinearLineSegment(PointF[])`](https://github.com/SixLabors/ImageSharp.Drawing/blob/c29e5de8bb1ed0afd11d71cb75ede5fd4bee0644/src/ImageSharp.Drawing/Shapes/LinearLineSegment.cs#L46-L53) constructor takes ownership of the array without copying, this makes sense since it would avoids an allocation and a copy for the user, but note that with Span (or rather ReadOnlySpan) the constructor is forced to do a copy. Do we want the Span and the ROS constructor to behave differently? If most users will fill these things from arrays anyways, maybe we just want to keep these API-s oldschool, and array-only?

**Comment by JimBobSquarePants** [comment]
Old school it is then!

**Comment by JimBobSquarePants** [comment]
It looks like we've covered this now. Closing

**Comment by antonfirsov** [comment]
I didn't mean this just for `ComplexPolygon`, `Path` and `Polygon` could use a similar constructors.

**Comment by antonfirsov** [comment]
I expect most real-life paths and polygons to be created given a list of points, yet there is no way for feeding those points directly to `Path` and `Polygon` constructors. A user needs to create `LinearLineSegment` around them first. We need `Path(PointF[])` and `Polygon(PointF[])` constructors.
