### ISSUE TITLE
Improve blending performance, make sure API is not a blocker

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp.Drawing#102]
After merging #96, blending will be the bottleneck in drawing. To address this I suggest to prototype batched variant of `NormalSrcOver` in the core library, preferably for 1.0 to make sure we can handle it with the current API without breaking changes.

![image](https://user-images.githubusercontent.com/6835152/99101431-e5996400-25dc-11eb-8143-b4cc2d86a1bc.png)

**Comment by antonfirsov** [comment]
Not realistic for 1.0

**Comment by JimBobSquarePants** [comment]
We need to have a dicussion regarding which version of ImageSharp we should be based on. We have our new fast blending implementation in V3.

**Comment by JimBobSquarePants** [comment]
Main now points at v3 now so I'm closing this.
