### ISSUE TITLE
Remove Region and implement "ProcessInsideShape" within ImageSharp.Drawing

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp.Drawing#105]
We want to enable clipping interest region of arbitrary processors by an arbitrary polygon. If we agree that solving this problem with `Region` is not feasible, we need to remove that type for 1.0, and add the [`ProcessInsideShape` utility](https://github.com/SixLabors/Samples/blob/32557bf359066c07358572e7147e638608522503/ImageSharp/CustomImageProcessor/Program.cs#L43-L46) to the core library.

For more details, see the discussion starting with https://github.com/SixLabors/ImageSharp.Drawing/pull/96#discussion_r512502959.

**Comment by JimBobSquarePants** [comment]
This means removing (not refactoring) any current extensions utilizing `Region` yes?

- `ClearRegionExtensions`
- `FillRegionExtensions`

We'd then keep `ShapeRegion` as an internal type to use in `FillRegionProcessor`

**Comment by antonfirsov** [comment]
Yes, we should remove them, just let's make sure we have equivalent functionality in other extension classes using `IPath`.
