### ISSUE TITLE
Simplified Chinese text wrapping does not take effect

### ISSUE THREAD

**Issue by StandOutstar** [SixLabors/ImageSharp.Drawing#115]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce

1. create a .net 5 console app
2. install SixLabors.ImageSharp.Drawing  version 1.0.0-beta11
3. load a image, then write simplified chinese text

```csharp
image.Mutate(x => x.
    DrawText(
        new TextGraphicsOptions()
        {
            TextOptions = new TextOptions
            {
                WrapTextWidth = 800,
            }
        }, 
        "这是一段长度超出设定的换行宽度的文本，但是没有在设定的宽度处换行。这段文本用于演示问题。希望可以修复。如果有需要可以联系我。",
        textFont,
        Color.Black,
        new PointF(300, 200)
    ));
```

### System Configuration

- ImageSharp version: 1.0.0-beta11
- Other ImageSharp packages and versions: 
- Environment (Operating system, version and so on): macOS 10.15.7
- .NET Framework version: 5.0.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
Confirmed using the following code with ImageSharp.Drawing 1.0.0-beta11.2 on Windows.

```c#
using SixLabors.Fonts;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using System.IO;

namespace ISD_115
{
    class Program
    {
        static void Main(string[] args)
        {
            var fonts = new string[] { "SimSun", "NSimSun" };

            for (int i = 0; i < fonts.Length; i++)
            {
                using (var image = new Image<Rgba32>(1100, 200, Color.White))
                {
                    image.Mutate(x => x.DrawText(
                        new TextGraphicsOptions()
                        {
                            TextOptions = new TextOptions
                            {
                                WrapTextWidth = 400,
                            }
                        },
                        "这是一段长度超出设定的换行宽度的文本，但是没有在设定的宽度处换行。这段文本用于演示问题。希望可以修复。如果有需要可以联系我。",
                        SystemFonts.Find(fonts[i]).CreateFont(16),
                        Color.Black,
                        Point.Empty));

                    image.Save(Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), $"../../../output/{fonts[i].ToLower()}.png")));
                }
            }

        }
    }
}

```
NSimSun
![nsimsun](https://user-images.githubusercontent.com/385879/102215064-1832c700-3ed1-11eb-8635-c63ed24bf7d7.png)

SimSun
![simsun](https://user-images.githubusercontent.com/385879/102215069-18cb5d80-3ed1-11eb-967e-748bc24f92ea.png)

**Comment by tocsoft** [comment]
This is due to the face we only have rules for whitespace based wrapping and Chinese generally doesn't use whitespace for wrapping it has some other system.

We would need/want to look at implementing the real full [unicode line breaking  algorithm](https://unicode.org/reports/tr14/). to support this correctly.

**Comment by JimBobSquarePants** [comment]
Just found an implementation with MIT license we could potentially use to help us implement. https://github.com/foliojs/linebreak
