### ISSUE TITLE
Shapes: Internal ClipperException thrown by `GenerateOutline`

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp.Drawing#13]
```csharp
PointF naan = new PointF(float.NaN, float.NaN);
Polygon path = new Polygon(new LinearLineSegment(new[] { naan, naan, naan, naan }));

// Throws internal exception:
path.GenerateOutline(10);
```

We should not throw internal exceptions, which are not communicated on the API surface.
Probably worth to review the library for more cases like this.

**Comment by antonfirsov** [comment]
Easy to fix, part of API cleanup, I believe we should do it for 1.0.

**Comment by obayomy** [comment]
@antonfirsov  
I was working on this issue when I noticed your recent comment and don't know if it is still possible to PR. My change is to move the (ClipperOffset) calls to a wrapper where such cases could be checked and throws the (ClipperException), should I make a PR?

**Comment by obayomy** [comment]
@antonfirsov  
I was working on this issue when I noticed your recent comment and don't know if it is still possible to PR. My change is to move the (ClipperOffset) calls to a wrapper where such cases could be checked and throws the (ClipperException), should I make a PR?

**Comment by antonfirsov** [comment]
@obayomy yes please! We should translate `ClipperException` to an `InvalidOperationException`.
