### ISSUE TITLE
DrawText() does not work with strings containing Japanese spaces.

### ISSUE THREAD

**Issue by chanuko** [SixLabors/ImageSharp.Drawing#131]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

- Case 1: Drawing a full-width space (IDEOGRAPHIC SPACE` `:`U+3000`) causes garbled characters.
- Case 2: When drawing a string containing two or more full-width spaces (IDEOGRAPHIC SPACE` `:`U+3000`) in multi-threaded mode, `System.ArgumentOutOfRangeException` occurs.

### DrawText

https://github.com/chanuko/ImageSharpBugReproduction/blob/99394dcf04f079177cb0ee340884bf6d918cf372/ConsoleApp1/CardCanvas.cs#L12-L33

#### Case1.
- It needs to be commented out at runtime.

https://github.com/chanuko/ImageSharpBugReproduction/blob/99394dcf04f079177cb0ee340884bf6d918cf372/ConsoleApp1/Program.cs#L10-L13

- Output image
![case1_001](https://user-images.githubusercontent.com/6064564/116050295-452e8c00-a6b2-11eb-87cf-b7bb3cde1643.jpg)

#### Case2.

https://github.com/chanuko/ImageSharpBugReproduction/blob/99394dcf04f079177cb0ee340884bf6d918cf372/ConsoleApp1/Program.cs#L15-L23

### What I've noticed

- The value of `GlyphLayout.IsWhiteSpace` is false for EM SPACE` `:`U+2003` and IDEOGRAPHIC SPACE` `:`U+3000`.

https://github.com/SixLabors/Fonts/blob/e5727d19af7a170701d5a9d677876313cf9316c1/src/SixLabors.Fonts/TextRenderer.cs#L76

#### Solution

- I was able to confirm that fixing this decision solved the problems in case 1 and case 2.
- I think changing the whitespace check from `codepoints[i] == ' '` to `char.IsWhiteSpace(text[i])` will solve the problem.

https://github.com/SixLabors/Fonts/blob/e5727d19af7a170701d5a9d677876313cf9316c1/src/SixLabors.Fonts/TextLayout.cs#L176
https://github.com/SixLabors/Fonts/blob/e5727d19af7a170701d5a9d677876313cf9316c1/src/SixLabors.Fonts/TextLayout.cs#L292

### System Configuration

- ImageSharp version: v1.0.3
- ImageSharp.Drawing version: v1.0.0-beta11
- Environment (Operating system, version and so on):Microsoft Windows 10 Pro 10.0.19042 Build 19042
- .NET Framework version:4.6.1
- Additional information:

**Comment by JimBobSquarePants** [comment]
Hi @chanuko 

Since you are building from source would you be able to confirm for me whether the version of Fonts in this PR https://github.com/SixLabors/Fonts/pull/160 fixes the issues? I've been working on a much more robust detection system based upon the Unicode standard.

Thanks!

**Comment by chanuko** [comment]
Hi @JimBobSquarePants 

I checked the operation with the branch of PR you presented, and confirmed that this problem has been solved.
However, I would like to install and use it via nuget, so I am hoping it will be released :)

Thanks!

**Comment by chanuko** [comment]
取り組んで頂きありがとうございます。
そのPRが1.0.0-rc.1としてマイルストーンが設定されていることを見ました。
1.0.0-rc.1がNugetでリリースされる時期の目処は立っているのでしょうか？

**Comment by chanuko** [comment]
Thank you for working on this.
I saw that the PR has a milestone set as 1.0.0-rc.1.
Do you have any idea when 1.0.0-rc.1 will be released on Nuget?

**Comment by JimBobSquarePants** [comment]
I can get that PR merged now and a release put on our MyGet feed for consumption however we were hoping to avoid a NuGet release until we could complete a few more [required features](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+needed%22) that would allow an RC release. Unfortunately there are currently no external contributors to the library so progress is very slow.

**Comment by chanuko** [comment]
I see.... Thanks for the information:)

**Comment by JimBobSquarePants** [comment]
I've released a new beta on NuGet containing your fix. 

https://www.nuget.org/packages/SixLabors.ImageSharp.Drawing/1.0.0-beta12
