### ISSUE TITLE
Beta12 nuget package lib for netcoreapp3.1 target has incorrect version of SixLabors.ImageSharp.Drawing.dll

### ISSUE THREAD

**Issue by starkna** [SixLabors/ImageSharp.Drawing#137]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Drawing
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When referencing the beta12 nuget package for netcoreapp3.1 target, the wrong version of the SixLabors.ImageSharp.Drawing.dll is included (0.0.0-alpha.0+39acb53427a-4b0d0f989c...) instead of the correct 1.0.0-beta12 version.

### Steps to Reproduce
Add nuget package reference for Sixlabors.ImageSharp.Drawing beta 12 to netcoreapp3.1 (or net5.0) project).

### System Configuration
N/A

- ImageSharp.Drawing version:  beta12
- Other ImageSharp packages and versions:  N/A
- Environment (Operating system, version and so on):  Windows 10 20H2
- .NET Framework version: Net5.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
@starkna thanks for raising this! 

I've confirmed there's definitely an issue and it's only affecting the Core3.1 build. I'll have a look at our build process and if I can identify a fix will release a new beta today.

![image](https://user-images.githubusercontent.com/385879/119511058-f8e67280-bd69-11eb-9ad2-a1ff5685986e.png)

**Comment by starkna** [comment]
@JimBobSquarePants Thanks for the quick reply - appreciate it!

**Comment by JimBobSquarePants** [comment]
It's definitely an odd one and doesn't seem to affect any of our other repos with identical setup. I'm experimenting with a simplified build process to see if I can narrow a cause down.

**Comment by JimBobSquarePants** [comment]
Nope. I'm stumped. There's no justification for this I can find.

https://github.com/SixLabors/ImageSharp.Drawing/runs/2667132314?check_suite_focus=true#step:5:15

**Comment by JimBobSquarePants** [comment]
I've asked in the MinVer repo
https://github.com/adamralph/minver/discussions/518

**Comment by JimBobSquarePants** [comment]
Switching to Ubuntu works for now. I've released a new beta 13 and de-listed beta 12.

https://www.nuget.org/packages/SixLabors.ImageSharp.Drawing/1.0.0-beta13
