### ISSUE TITLE
Improve accuracy of drawing text along a path

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ImageSharp.Drawing#159]
Modify `PathGlyphBuilder`

https://github.com/SixLabors/ImageSharp.Drawing/blob/653cf5f8f6249c8e5432ad992e42a721d8638003/src/ImageSharp.Drawing/Shapes/Text/PathGlyphBuilder.cs#L39-L49

To more accurately transform individual glyph paths.

As demonstrated in the samples project the glyphs are not evenly aligned along the path.

https://github.com/SixLabors/ImageSharp.Drawing/blob/653cf5f8f6249c8e5432ad992e42a721d8638003/samples/DrawShapesWithImageSharp/Program.cs#L68-L81

![Hello World Hello World Hello World Hello World Hello World Hello World Hello World](https://user-images.githubusercontent.com/385879/128010990-2b07bfda-5254-405c-be44-10814bbb8c10.png)

This article describes how to accurately draw text along a path.
http://www.planetclegg.com/projects/WarpingTextToSplines.html

**Comment by JimBobSquarePants** [comment]
Relevant SkiaSharp issue which should provide some valuable insight.
https://github.com/mono/SkiaSharp/issues/1183

**Comment by JimBobSquarePants** [comment]
Additional issue demo.

![Hello World Hello World Hello World Hello World Hello World Hello World Hello World](https://user-images.githubusercontent.com/385879/128127153-6b8e2a0f-28ff-4f87-b282-7e1eedf9b6fc.png)

**Comment by JimBobSquarePants** [comment]
@SixLabors/core I think we should priorities this incase we need to make any changes to `IGlyphRenderer` in the Fonts library.

**Comment by tocsoft** [comment]
I can't see how it would require changes to the IGlyphRenderer... all glyph renders does is act an abstraction to feed out the code points for the vectors (and color info as required)... the mutation of the points to allow distorting along a path is all done in vector space.

**Comment by JimBobSquarePants** [comment]
As long at there’s enough info passed through then that’s ok. I’m just confused how what appears to me should be a simple transform can go so wrong.

**Comment by JimBobSquarePants** [comment]
Looks like the new Fonts layout engine is a big improvement.

OLD
![image](https://user-images.githubusercontent.com/385879/142408850-32db911d-1e81-463b-9222-649eb45efdc1.png)

NEW
![Hello World Hello World Hello World Hello World Hello World Hello World Hello World](https://user-images.githubusercontent.com/385879/142408710-5cbaa702-486e-41df-b7f4-e29052599636.png)

**Comment by JimBobSquarePants** [comment]
Remaining oddities (Look at the capital W) appear to be caused by the rotation taking place against the bottom/left corner of each glyph rather than the bottom center. I've hacked at this a few times now but lack the matrix maths knowledge to fix it.
