### ISSUE TITLE
FillPolygon ImageBrush as crop not texture

### ISSUE THREAD

**Issue by agrath** [SixLabors/ImageSharp.Drawing#16]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp [built from master/source]
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When calling FillPolygon using an ImageBrush, the source image is sampled from an origin of 0,0
This can be traced to ImageBrush being initialized with a region representing the polygon, meaning the rectangle passed as an origin of minX, minY of the source polygon and is pre-offset.
When FillPolygon is then iterating the Y scanlines, it is passing an incrementing Y and an origin X but inside Apply, the originally passed region is used to create an offsetX/offsetY which in this case, causes the sourceX and sourceY to start at 0 and increment as FillPolygon calls Apply for each scan line.

### Steps to Reproduce
```
void Main()
{
	string path = @"C:\Users\User\Source\Repos\PrimitiveSharp\PrimitiveSharp.Web\Media\photo-1486218119243-13883505764c.jpg";
	using (Image<Rgba32> brushImage = Image.Load(path))
	{
		var resizedBrush = brushImage.Clone(x => x.Resize(500,500));
		Debug(resizedBrush);
		
		Debugger.Break();
		var simplePath = new SixLabors.Primitives.PointF[] {
				new Vector2(300, 127),
				new Vector2(216, 401),
				new Vector2(433, 258)
		};

		using (var image = new Image<Rgba32>(500, 500))
		{
			var brush = new ImageBrush<Rgba32>(resizedBrush);

			image.Mutate(x => x
				.BackgroundColor(Rgba32.Blue)
				.FillPolygon(brush, simplePath));

			Debug(image);
		}


	}
}

private void Debug(Image<Rgba32> image)
{
	using (MemoryStream ms = new MemoryStream())
	{
		image.SaveAsJpeg(ms);
		ms.Position = 0;
		using (System.Drawing.Bitmap b = (System.Drawing.Bitmap)System.Drawing.Bitmap.FromStream(ms))
		{
			b.Dump();
		}
	}
}
```

### System Configuration

- ImageSharp version: Latest built from master
- Other ImageSharp packages and versions: Latest built from master
- Environment (Operating system, version and so on): n/a but Win10
- .NET Framework version: 4.7 
- Additional information: See gitter channel for sample images and a discussion

**Comment by antonfirsov** [comment]
Triaging to future for now, but I must admit, I don't follow the problem. @tocsoft do you think there is a valuable feature request for the wider public? If not, let's close.

**Comment by JimBobSquarePants** [comment]
> I want to use a polygon to apply a mask to a DrawImage.

Is this not covered by our clipping functionality now? I.E draw then clip?

**Comment by tocsoft** [comment]
yeah the [`ctx.Clip(..)`](https://docs.sixlabors.com/api/ImageSharp.Drawing/SixLabors.ImageSharp.Drawing.Processing.ClipPathExtensions.html#SixLabors_ImageSharp_Drawing_Processing_ClipPathExtensions_Clip_IImageProcessingContext_SixLabors_ImageSharp_Drawing_IPath_System_Action_IImageProcessingContext__) operation extension allow for this
