### ISSUE TITLE
Support for RTL text

### ISSUE THREAD

**Issue by JamieMagee** [SixLabors/ImageSharp.Drawing#17]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

System.Drawing has the option `StringFormatFlags.DirectionRightToLeft` (See [this StackOverflow](https://stackoverflow.com/a/11607403) answer for an example). Is there any support for a similar option, or any intention to provide one?

**Comment by antonfirsov** [comment]
@JimBobSquarePants I remember you mentioning you want to push this out of 1.0. Is this correct, or is it any realistic to achieve for RC1?

Triaging to Future for now.

**Comment by JimBobSquarePants** [comment]
I think Future is more accurate here.  We lack the community involvement to consider a V1 release.

**Comment by JimBobSquarePants** [comment]
I've just pushed an update into the MyGet feed `1.0.0-beta13.15` which adds Bidi support to text drawing. We'll automatically detect the direction (_we support mixed LTR and RTL automatically_) but you can force a single direction if you want also. 

Please bear in mind that there's are still some [language specific font shapers to implement](https://github.com/SixLabors/Fonts/issues?q=is%3Aissue+is%3Aopen+label%3Ashaping) (_help needed and appreciated there_) so there might still be some quirks.
