### ISSUE TITLE
FontStyle.Italic no work

### ISSUE THREAD

**Issue by Coloryr** [SixLabors/ImageSharp.Drawing#183]
- ImageSharp.Drawing version:1.0.0-beta13
- Other ImageSharp packages and versions: SixLabors.ImageSharp-1.0.4
- Environment (Operating system, version and so on): win11
- .NET Framework version: net6.0
- Additional information:
code:
```C#
using SixLabors.Fonts;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Drawing.Processing;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;

FontFamily fontFamily = SystemFonts.Families.Where(a => a.Name == "微软雅黑").FirstOrDefault();
var font_italic = fontFamily.CreateFont(20, FontStyle.Italic);
Image img = new Image<Rgba32>(300, 100);
var graphicsOptions = new GraphicsOptions()
{
    Antialias = true,
    AntialiasSubpixelDepth = 256
};
img.Mutate((operation) =>
{
    operation.SetGraphicsOptions(graphicsOptions);
    operation.Clear(Color.Black);
    operation.DrawText("Hello World", font_italic, Color.White, new PointF(0,0));
});
img.SaveAsPng("test.png");
```
![ZVT9}@43JZ2GO %NH)8Z802](https://user-images.githubusercontent.com/26276037/145153825-f298e7d8-6125-435c-ac93-9351e4fe4b56.png)

**Comment by tocsoft** [comment]
please ensure you have an italic version of the font installed in a place the `SystemFonts` collection can discover it.

If in doubt and to validate if its a bug in the render or its a lack of a font existing its always better to bypass the `SystemFonts` collection and instead create a custom `FontCollection` manually add the ttf fonts yourself (ensuring you add all the variants you require) and verify if it works as expected there. 

Things like bold, italic, regular fonts will generally be separate font files.

P.S. it seems you are trying to use `Microsoft YaHei` ... that font doesn't seem to come in italic at all so it will never render that way with our library.... Some software can fake out the italic slant if its missing from the original font, we don't have that capability.
