### ISSUE TITLE
Draw text wrapped inside rectangle

### ISSUE THREAD

**Issue by kolpav** [SixLabors/ImageSharp.Drawing#19]
It would be nice to be able to draw text inside of rectangle basically replicate [feature](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-draw-wrapped-text-in-a-rectangle) present in System.Drawing.

![image](https://user-images.githubusercontent.com/19467143/61455762-c6e17980-a964-11e9-98f9-f4156b48467d.png)

Currently it is possible to wrap text at certain width using `WrapTextWidth` but I would like to have control over vertical axis as well. I want to precisely place text over image knowing it won't grow outside its defined bounds. Having ability to define text alignment would be super useful too like you can do with [TextFormatFlags](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.textformatflags?view=netframework-4.8).

Please consider adding this feature.

**Comment by antonfirsov** [comment]
This seems like a very useful feature, but I doubt we can make it into 1.0, moving to Future.

**Comment by SirusDoma** [comment]
Hey, I know that you said that you might not be able to make it into 1.0 but is there any clear estimation on this? I'd really like to see this feature. Oh I'm not really experienced with text rendering, but is there any pointer where one could contribute on this?

Also is it possible to calculate `DrawText` area before hand? that might be useful as well

**Comment by JimBobSquarePants** [comment]
We'll definitely have comprehensive text wrapping support with multiple word breaking options and text align. What I'm unsure of though is clipping in the vertical direction. @tocsoft That would just be a case of recognizing we've hit a vertical limit and stopping no?

**Comment by tocsoft** [comment]
you can make use of https://github.com/SixLabors/ImageSharp.Drawing/blob/5bbf20e6cff00d06e9a6c61ea79c31e48ed824df/src/ImageSharp.Drawing/Processing/Extensions/ClipPathExtensions.cs#L22 (I believe this is only in the [nightlies feed](https://github.com/SixLabors/ImageSharp.Drawing#installation)) to apply the drawing operation and ensure its explicitly clipped.

**Comment by JimBobSquarePants** [comment]
Ah yes, I’d forgotten about that.

**Comment by antonfirsov** [comment]
@SirusDoma dumb, slow heuristic approach, but might be good enough:
you can use repeated calls of `TextMeasurer.Measure` to get a size that approximately fits your destination area, then maybe using resize to fine-tune it.

**Comment by JimBobSquarePants** [comment]
The combination of wrapping + clipping is what the System.Drawing example is doing above. We've had both methods for a long time now on NuGet so I'm closing this.
