### ISSUE TITLE
Doc issue

### ISSUE THREAD

**Issue by VShawn** [SixLabors/ImageSharp.Drawing#193]
### Description
missing `;`

![image](https://user-images.githubusercontent.com/10143738/148871622-844f9d1d-5697-4db2-b6fe-637949d5bcf6.png)

### Steps to Reproduce
open https://docs.sixlabors.com/articles/imagesharp.drawing/gettingstarted.html

### System Configuration
chrome

**Comment by JimBobSquarePants** [comment]
Thanks for this. 

We actually have a separate repository for documentation. On the top/right of the page you highlighted is a link [`IMPROVE THIS DOC`](https://github.com/SixLabors/docs/blob/master/articles/imagesharp.drawing/gettingstarted.md/#L1) where you can submit a PR with a fix.



![image](https://user-images.githubusercontent.com/385879/148874380-34ab9e79-6d41-4fe6-ab6b-998e11b3c894.png)

**Comment by VShawn** [comment]
@JimBobSquarePants  I see, I will go there. thx.
