### ISSUE TITLE
DrawText result is pixelated and have inconsistent result

### ISSUE THREAD

**Issue by warheat1990** [SixLabors/ImageSharp.Drawing#21]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I want to apply text to my images, but the result is inconsistent, the text becomes softer (like antialiased after the word "TES") when it overlaps the picture. Here's the example

![image](https://user-images.githubusercontent.com/4485011/68187832-48274f80-ffda-11e9-93ce-42e432ddc7d0.png)

Also notice that the "TEST123123" text is somewhat pixelated, so my question is

1. How to make the text consistent all across the pictures?
2. which settings should I use to make the text more more high quality while keeping the same size?

### Steps to Reproduce
```
using (Image<Rgba32> picture = Image.Load<Rgba32>(file)) // load up source images
                using (Image<Rgba32> output = new Image<Rgba32>(
                    settings.Template.Width,
                    settings.Template.Height)) // create output image of the correct dimensions
                {
                    //draw shape
                    foreach (var shape in settings.Shape)
                    {
                        output.Mutate(m => m.FillPolygon(Rgba32.FromHex(shape.Color), shape.Point.ToArray()));
                    }

                    //draw picture
                    picture.Mutate(o => o.Resize(new ResizeOptions()
                    {
                        Mode = ResizeMode.Pad,
                        Size = new Size(settings.Picture.Width, settings.Picture.Height)
                    }));
                    output.Mutate(m => m.DrawImage(picture, new Point(settings.Picture.X, settings.Picture.Y), 1));

                    //draw text
                    foreach (var word in settings.Word)
                    {
                        output.Mutate(m => m.DrawText(
                                new TextGraphicsOptions(true)
                                {
                                    WrapTextWidth = word.Width,
                                    HorizontalAlignment = word.Alignment,
                                    ApplyKerning = true
                                },
                                word.Text,
                                new Font(fonts.Find(word.FontFamily), word.Size, word.Style),
                                Rgba32.FromHex(word.Color),
                                new PointF(word.X, word.Y)
                            )
                        );
                    }

                    //draw watermark
                    foreach (var watermark in settings.Watermark)
                    {
                        output.Mutate(m => m.DrawText(
                                new TextGraphicsOptions(true)
                                {
                                    WrapTextWidth = watermark.Width,
                                    HorizontalAlignment = watermark.Alignment,
                                    ApplyKerning = true
                                },
                                watermark.Text,
                                new Font(fonts.Find(watermark.FontFamily), watermark.Size, watermark.Style),
                                Rgba32.FromHex(watermark.Color),
                                new PointF(watermark.X, watermark.Y)
                            )
                        );

                        var f = new FileInfo(file);
                        var directoryName = f.DirectoryName + "\\" + settings.Name + "\\" + watermark.Name;
                        System.IO.Directory.CreateDirectory(directoryName);
                        output.Save(
                            directoryName + "\\" + Path.GetFileNameWithoutExtension(f.Name) + ".png",
                            new PngEncoder() { CompressionLevel = 1 }
                        );
                        Console.WriteLine(directoryName + "\\" + Path.GetFileNameWithoutExtension(f.Name) + ".png created.");
                    }
                }
```
### System Configuration

- ImageSharp version: 1.0.0-beta0007
- Other ImageSharp packages and versions: 1.0.0-beta0007
- Environment (Operating system, version and so on): Windows 10
- .NET Framework version: Net Core 3.0
- Additional information:

**Comment by KinsonDigital** [comment]
I myself have done a very simple example and rendered some text using a font loaded with **SixLabors.Fonts** and rendered the text to an all-white 200 x 200 png image.  The quality was not great.

Maybe there are settings that can be used to increase the render quality during image.Mutate()?

![image](https://user-images.githubusercontent.com/4921022/112384734-26109900-8cc5-11eb-8cf7-403c41192ec0.png)

**Comment by JimBobSquarePants** [comment]
@KinsonDigital Can you please provide some more information. 

I.E what library versions you are using (Drawing, Fonts) and what font is being used.

A code sample would be very useful otherwise.

**Comment by KinsonDigital** [comment]
Not a problem.  Attached is a zipped-up sample project.  If you have any questions, don't hesitate to ask.

Thanks!!
[FontPlayground.zip](https://github.com/SixLabors/ImageSharp.Drawing/files/6201397/FontPlayground.zip)

**Comment by KinsonDigital** [comment]
A little more context on what I am trying to do.

I am developing a game engine/framework and I am working on rendering text to the screen.  What I am planning on doing is to use this to generate a [Texture Atlas](https://en.wikipedia.org/wiki/Texture_atlas) that contains each letter, number, and symbol.

With this texture atlas, I will render these individual symbols/glyphs to the screen using OpenGL (OpenTK).

I want to make sure that not only are all of the glyphs rendered to the image surface to save space in a grid-like pattern, but also have them render at a high quality.

This means I also need to be able to get information on the size of each letter as I render it so I can lay them out in the atlas appropriately. 

So I have so far the letters **a**, **b**, **c** rendering out in a single row.  When I increased the `TextOptions.DpiX` and `TextOptions.DpiY` from 72 to 144, the letters increase in size but they are on top of each other.

Currently, I am just using `TextureMeasuer.Measure()` to get the width of the single letter and using that to figure out where to render the letter onto the image/surface.

Is there a way to get the width of the text and to take the DPI into account so when I increase the DPI the X coordinate placement does not end up on top of each other?

I feel like what I am gonna have to do is calculate the X coordinate position to take the DPI into account somehow.

---

Here are the results:

**72 DPI:**
![image](https://user-images.githubusercontent.com/4921022/112452728-4e33e280-8d2d-11eb-9601-460f69bcb6ed.png)

**144 DPI:**
![image](https://user-images.githubusercontent.com/4921022/112452769-5ab83b00-8d2d-11eb-91b7-c68ed153c7b6.png)

---

Code that produces results:

``` cs
var fonts = new FontCollection();
var letters = new[] { 'a', 'b', 'c' };


var family = fonts.Install(_fontFilepath);
var font = family.CreateFont(22, FontStyle.Regular);

var renderOptions = new RendererOptions(font, dpi: 72)
{
    ApplyKerning = true,
};


var textGrfxOptions = new TextGraphicsOptions()
{
    TextOptions = new TextOptions()
    {
        ApplyKerning = true,
        TabWidth = 4,
        WrapTextWidth = 0,
        HorizontalAlignment = HorizontalAlignment.Left,
        DpiX = 144,
        DpiY = 144,
    },
};

var text = "sample text";

var image = Image.Load($@"{_basePath}RenderSurface.png");

var xPos = 0f;

for (int i = 0; i < letters.Length; i++)
{
    var rect = TextMeasurer.Measure(letters[i].ToString(), renderOptions);

    if (i > 0)
    {
        xPos += rect.Width;
    }

    image.Mutate(context => context.DrawText(textGrfxOptions, letters[i].ToString(), font, Color.Black, new PointF(xPos, 0)));
}     
```

**Comment by KinsonDigital** [comment]
Once of the things I am running into is how to calculate the space between each character for laying them out horizontally.

If I use the `FontRectangle.Width`, I get the results below:
![image](https://user-images.githubusercontent.com/4921022/112455374-082c4e00-8d30-11eb-9b94-e9ec49e41a1e.png)

How would I go about knowing how to place the letters?
I would imagine that I need glyph metrics like below?
![image](https://user-images.githubusercontent.com/4921022/112455531-327e0b80-8d30-11eb-977f-457aba990e06.png)

---

Code used to produce current result:

``` cs
var fonts = new FontCollection();
var glyphs = new[] { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z' };
var dpi = 72;

var glyphRects = new Dictionary<char, FontRectangle>();

var family = fonts.Install(_fontFilepath);
var font = family.CreateFont(22, FontStyle.Regular);

var renderOptions = new RendererOptions(font, dpi: dpi)
{
    ApplyKerning = true,
};


foreach (var glyph in glyphs)
{
    glyphRects.Add(glyph, TextMeasurer.Measure(glyph.ToString(), renderOptions));
}

var textGrfxOptions = new TextGraphicsOptions()
{
    TextOptions = new TextOptions()
    {
        ApplyKerning = true,
        TabWidth = 4,
        WrapTextWidth = 0,
        HorizontalAlignment = HorizontalAlignment.Left,
        DpiX = dpi,
        DpiY = dpi,
    },
};

var image = Image.Load($@"{_basePath}RenderSurface.png");

var firstIteration = true;
var xPos = 0f;

foreach (var glyph in glyphRects)
{
    if (firstIteration is false)
    {
        xPos += glyph.Value.Width;
    }

    image.Mutate(context => context.DrawText(textGrfxOptions, glyph.Key.ToString(), font, Color.Black, new PointF(xPos, 0)));

    firstIteration = false;
}
```

**Comment by KinsonDigital** [comment]
After some more research, I have found that the `GlyphInstance` might have what I need.  I noticed it has an `AdvanceWidth` property which I am suspecting that is what I need.

One thing that I am unclear about though is the `codePoint` parameter in the `Font.GetGlyph()` method.

What is a code point and what would I choose?  Is `codePoint` the font size in points? 

Thanks!!

**Comment by tocsoft** [comment]
You can use a custom `IGlyphRenderer` to access fine details about the layed out text. All you have to do is, during the during the `BeginGlyph()` api call return `false` to indicate that you don't need the rest of the glyph data (as you will instead use the target rect and your lookup in your atlas data for your specific glyph). 

Basically don't worry about trying to layout the text yourself, let `Fonts` do if for you, and just worry about drawing the bitmaps to screen.

**Comment by tocsoft** [comment]
Our internal rendering code actually uses an atlas of sorts for our own rendering maybe that could help inspire you on an approach without having to reinvent text layout.  

https://github.com/SixLabors/ImageSharp.Drawing/blob/c29e5de8bb1ed0afd11d71cb75ede5fd4bee0644/src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor%7BTPixel%7D.cs#L180

**Comment by JimBobSquarePants** [comment]
@KinsonDigital I had a look at your sample and compared the output of the latest MyGet versions with the version on NuGet and also Paint.NET

- Top Paint.NET
- Middle ImageSharp.Drawing 1.0.0-beta11, Fonts 1.0.0-beta0013
- Bottom ImageSharp.Drawing 1.0.0-beta11.4, Fonts 1.0.0-beta13.5.6

I think we've lost something on the very bottom of the 'p' but are rendering much sharper for all other characters.

This image is zoomed in by 800%. 

![image](https://user-images.githubusercontent.com/385879/112553708-e9c06400-8dbc-11eb-9cd9-d35c55785646.png)

At real size I think it's much more clear.

![output](https://user-images.githubusercontent.com/385879/112554199-c5b15280-8dbd-11eb-86b6-1d541c5e3ccf.png)

**Comment by KinsonDigital** [comment]
Thanks guys!!  Awesome!!  I will play around with this info you gave me and see what I can come up with.  🙂

**Comment by KinsonDigital** [comment]
> Our internal rendering code actually uses an atlas of sorts for our own rendering maybe that could help inspire you on an approach without having to reinvent text layout.
> 
> https://github.com/SixLabors/ImageSharp.Drawing/blob/c29e5de8bb1ed0afd11d71cb75ede5fd4bee0644/src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor%7BTPixel%7D.cs#L180

@tocsoft I have been looking at this code in the link above but I will not lie, I am struggling with what some of the methods are for and what they do as well as how I would even use my implementation once I have it built.

Could you possibly give me some guidance?

**Comment by JimBobSquarePants** [comment]
Hey @KinsonDigital can you do me a favour and please take any questions over to the [Discussions channel](https://github.com/SixLabors/ImageSharp.Drawing/discussions/categories/q-a)?

I want to close this issue as I don't think our font rendering suffers from the same issues any more.

![RenderResult](https://user-images.githubusercontent.com/385879/112640710-7a3c8a00-8e39-11eb-9aef-f406835c5198.png)

**Comment by KinsonDigital** [comment]
Absolutely.  Thanks for the help!!

**Comment by KinsonDigital** [comment]
Actually, I do have similar discussions going on in the discussion channel for the **SixLabors.Fonts** repo.

What would be a better place?

**Comment by JimBobSquarePants** [comment]
Yeah just carry on there. 👍
