### ISSUE TITLE
DrawTextProcessor memory leak from TessellatedMultipolygon 

### ISSUE THREAD

**Issue by br3aker** [SixLabors/ImageSharp.Drawing#215]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`DrawTextProcessor` leads to memory leaks, well, not *actual* leaks but undisposed memory buffers.
Actual chain of 'responsibility': `DrawTextProcessor` -> `PolygonScanner` -> `TessellatedMultipolygon`

`TessellatedMultipolygon` is allocated and used by `PolygonScanner` here:
https://github.com/SixLabors/ImageSharp.Drawing/blob/241891b7db29786ab82c4b03344ee41567e96bba/src/ImageSharp.Drawing/Shapes/Rasterization/PolygonScanner.cs#L93-L106

It's also allocated here:
https://github.com/SixLabors/ImageSharp.Drawing/blob/241891b7db29786ab82c4b03344ee41567e96bba/src/ImageSharp.Drawing/Shapes/Rasterization/ScanEdgeCollection.cs#L38-L45

Both cases are used to create `ScanEdgeCollection` which does not use it after `Create` method so we hopefully can safely add `using` statement for both cases and call it a day.

### Steps to Reproduce
See https://github.com/SixLabors/ImageSharp/issues/2079

**Comment by JimBobSquarePants** [comment]
Yep. That looks sensible. I'll run some tests later. 

Thinking in the open, we should probably add an assertation in all our tests.

``` c#
Assert.Equal(0, MemoryDiagnostics.TotalUndisposedAllocationCount);
```

**Comment by tocsoft** [comment]
> Yep. That looks sensible. I'll run some tests later.
> 
> Thinking in the open, we should probably add an assertation in all our tests at some point.
> 
> ```cs
> Assert.Equal(0, MemoryDiagnostics.TotalUndisposedAllocationCount);
> ```

should be covered/do able using the proposed helpers from #216 (which includes a fix for this issue)
