### ISSUE TITLE
DrawText with translucent color, the alpha pixel not blend.

### ISSUE THREAD

**Issue by ZhuXiaoChun** [SixLabors/ImageSharp.Drawing#243]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
DrawText with translucent color, the alpha pixel not blend，like this:
`
image.Mutate(imageProcessingContext =>
{

        var font = SystemFonts.CreateFont("Arial", 100);
        imageProcessingContext.DrawText(
                "Abcdefghijklmnopqrstuvwxyz",
                font,
                Color.FromRgba(0, 0, 0, 128),
                new Point(0, 0));
});
`

### Steps to Reproduce
DrawText with translucent color.

### System Configuration
Microsoft Visual Studio Community 2022 (64 Bits) - Current
Versions 17.3.1

- ImageSharp.Drawing version: 1.0.0-beta15
- Other ImageSharp packages and versions: none
- Environment (Operating system, version and so on):
- .NET Framework version: .Net Core 6.0.4
- Additional information:
Sample Project:
https://github.com/ZhuXiaoChun/Test.ImageSharp.DrawText

**Comment by atruskie** [comment]
What pixel format is your image?

If it is Rgb24 you might be running into the same issue I had: https://github.com/SixLabors/ImageSharp.Drawing/issues/38

**Comment by ZhuXiaoChun** [comment]
> What pixel format is your image?
> Image load from png file, it's 24Bits.
> If it is Rgb24 you might be running into the same issue I had: #38
Yes, it's the same issue.

Thank you very much!
