### ISSUE TITLE
File names are too long

### ISSUE THREAD

**Issue by robertjb20** [SixLabors/ImageSharp.Drawing#262]
When using TortoiseGit on Windows 11 (Latest build and previously) or unzipping the archive, I receive the error message that the following file names are too long. Please shorten so that everyone using windows can use:

tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanDrawRichTextAlongPathHorizontal_Solid100x100_(0,0,0,255)_RichText-Path-(spiral).png
tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanDrawRichTextAlongPathHorizontal_Solid120x120_(0,0,0,255)_RichText-Path-(triangle).png
tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/CanDrawRichTextAlongPathHorizontal_Solid350x350_(0,0,0,255)_RichText-Path-(circle).png
tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/DrawRichTextArabic_Solid500x200_(0,0,0,255)_RichText-Arabic-F(32).png
tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/DrawRichTextArabic_Solid500x300_(0,0,0,255)_RichText-Arabic-F(40).png
tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/DrawRichTextRainbow_Solid500x200_(0,0,0,255)_RichText-Rainbow-F(32).png
tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/DrawRichTextRainbow_Solid500x300_(0,0,0,255)_RichText-Rainbow-F(40).png
tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/DrawRichText_Solid500x200_(0,0,0,255)_RichText-F(32).png
tests/Images/ReferenceOutput/Drawing/Text/DrawTextOnImageTests/DrawRichText_Solid500x300_(0,0,0,255)_RichText-F(40).png

Thank you.

**Comment by tocsoft** [comment]
you have followed our instructions in the readme saying to enable long file names in git? `git config --system core.longpaths true`.

You can also try checking files out into a shorter root folder i.e. `c:\source\IS.Draw`

**Comment by JimBobSquarePants** [comment]
I actually got bitten by this myself recently. LFS doesn’t seem to respect long path (or I’ve missed something)

**Comment by robertjb20** [comment]
Good morning.


Sorry to reply so late. I use TortoiseGIT for my interface and cannot find where to set this value in the many dialog screens. Can you tell me where I can set this value? I don't want to manually do this every time.


Thank you.


Regards,




Robert&nbsp;Berridge
***@***.***







                       
Original
                       
                     

From:"Scott Williams"< ***@***.*** &gt;;

Date:2023/3/22 7:25

To:"SixLabors/ImageSharp.Drawing"< ***@***.*** &gt;;

CC:"robertjb20"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [SixLabors/ImageSharp.Drawing] File names are too long (Issue#262)




 
you have followed our instructions in the readme saying to enable long file names in git? git config --system core.longpaths true.
 
You can also try checking files out into a shorter root folder i.e. c:\source\IS.Draw

**Comment by JimBobSquarePants** [comment]
I don't use that software. You should use the console command as described above.
