### ISSUE TITLE
The ImageBrushApplicator indexer appears to have a bug, accessing the Width property instead of Height (ImageBrush.cs, line 140)

### ISSUE THREAD

**Issue by vargonian** [SixLabors/ImageSharp.Drawing#270]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
                    int srcY = ((y - this.offsetY) % this.sourceRegion.Width) + this.sourceRegion.Y;
                    
The line above appears to be a bug; is it supposed to be this.sourceRegion.Height instead?  This may explain an ArgumentOutOfRangeException I'm getting when I try to use an ImageBrush with DrawText when the font size is too large (apparently).                 

### Steps to Reproduce
N/A

### System Configuration
N/A

- ImageSharp.Drawing version:
- Other ImageSharp packages and versions:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by vargonian** [comment]
I see another potential issue, which may just be my misunderstanding of the code, on [line 73](https://github.com/SixLabors/ImageSharp.Drawing/blob/1d451a29c33be9cca3cf10879768fde9cf04ce1b/src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor%7BTPixel%7D.cs#LL73C25-L73C26) of DrawTextProcessor{TPixel}.cs:
`if (startX + buffer.Height < 0)`

I don't understand why it's comparing an X value with a Height but perhaps it's completely fine.  I'm only noticing this as I'm attempting to debug an issue drawing text with an ImageBrush (I'm getting an ArgumentOutOfRangeException in ImageBrushApplicator.Apply which may be related; I'll distill the problem and create a separate issue if not.)

**Comment by antonfirsov** [comment]
Thanks for spotting this! To me it looks like both mentioned lines are wrong.

> This may explain an ArgumentOutOfRangeException I'm getting when I try to use an ImageBrush with DrawText when the font size is too large (apparently).

Do you have a small repro by any chance?

**Comment by vargonian** [comment]
I'm happy to help!  Here is a repro for the ArgumentOutOfRangeException.  Some background information first: The versions of the packages I'm using:

SixLabors.Fonts (1.0.0-beta19)
SixLabors.ImageSharp (2.1.4)
SixLabors.ImageSharp.Drawing (1.0.0-beta15)

Also, it's important to note that in other ImageBrush systems I've used so far, the brush pattern automatically tiles to fit the target, so I'm making the assumption that it behaves that way here as well.  I've thought that perhaps it doesn't behave that way, and that's why setting a big font size causes the exception--_but_, it doesn't seem to matter in word-wrapping scenarios, i.e. even when the wrapped text would fit within the brush image size, the exception is still thrown.  Here is distilled code which reproduces the error:

```CSharp
public void ReproImageBrushException()
{
	const int targetImageWidth = 350;
	const int targetImageHeight = 350;
	const float maximumWorkingFontSize = 46;
	const float minimumCrashingFontSize = 47;
	const string imageBrushSourceImagePath = @"TestSamples/input/image-brush-texture/starfield-pattern-256.png";
	const string targetImagePath = @"c:\stuff\temp\sample-output\imagebrush-repro.png";
	const string text = "Hello, World!";

	Font font = SystemFonts.CreateFont("Arial", minimumCrashingFontSize);
	IPen pen = Pens.Solid(Color.Black, 1);
	using Image<Rgba32> targetImage = new Image<Rgba32>(targetImageWidth, targetImageHeight, Color.Wheat);
	using Image<Rgba32> imageBrushImage = Image.Load<Rgba32>(imageBrushSourceImagePath);
	ImageBrush imageBrush = new ImageBrush(imageBrushImage);

	targetImage.Mutate(x => x.DrawText(CreateTextOptions(font, targetImageWidth), text, imageBrush, pen));

	targetImage.Save(targetImagePath);
}

private TextOptions CreateTextOptions(Font font, int wrappingLength)
{
	TextOptions textOptions = new TextOptions(font)
	{
		Origin = new Vector2(175, 175),
		TextAlignment = TextAlignment.Center,
		LayoutMode = LayoutMode.HorizontalTopBottom, // I don't know what this does
		WrappingLength = wrappingLength,
		WordBreaking = WordBreaking.Standard,
		HorizontalAlignment = HorizontalAlignment.Center,
		VerticalAlignment = VerticalAlignment.Center,
		KerningMode = KerningMode.None,
	};

	return textOptions;
}
```
