### ISSUE TITLE
Drawing non-antialiased 1px high line at Y 0 coordinate is not rendered (coordinates seem to be off by 1)

### ISSUE THREAD

**Issue by atruskie** [SixLabors/ImageSharp.Drawing#28]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

 I'm trying to draw some non-antialiased 1px lines.

### Steps to Reproduce

```
        static void Main(string[] args)
        {
            var image = new Image<Rgb24>(Configuration.Default, 100, 100, Color.Black);
            image.Mutate(x => x.DrawLines(
                new ShapeGraphicsOptions() { Antialias = false },
                Color.Red,
                1f,
                new PointF(0, 0),
                new PointF(100, 0)
                ));

            image.Save("test.png");
        }
```

Actual output:
![test](https://user-images.githubusercontent.com/1452968/75151304-16392500-5752-11ea-990b-b065162b4d3a.png)

Expected:
![testExpected](https://user-images.githubusercontent.com/1452968/75151318-1d603300-5752-11ea-9957-ee3e8cf38b83.png)

### System Configuration

- ImageSharp.Drawing version: SixLabors.ImageSharp.Drawing 1.0.0-unstable0421
- Other ImageSharp packages and versions: SixLabors.ImageSharp 1.0.0-unstable0702
- Environment (Operating system, version and so on): Win 10, 19564.1000
- .NET Framework version: .NET Core 3.1.200-preview-014977
- Additional information:

For comparison, output from other cases follows:

### Using y-offset of 1

![test1](https://user-images.githubusercontent.com/1452968/75151388-4a144a80-5752-11ea-994c-6d98760e74d1.png)

### System.Drawing with y-offset of 0
```
            Bitmap b = new Bitmap(100, 100);
            var graphics = Graphics.FromImage(b);
            graphics.Clear(Color.Black);
            graphics.DrawLines(new Pen(Color.Red, 1), new[]
            {
                new PointF(0, 0),
                new PointF(100, 0)
            });


            b.Save("test_SD.bmp");
```

<img width="100" alt="test_SD" src="https://user-images.githubusercontent.com/1452968/75151498-8c3d8c00-5752-11ea-95d7-5762217d3cbc.png">

### SkiaSharp with y-offset of 0

```

            var image = new SKBitmap(new SKImageInfo(100, 100, SKColorType.Rgba8888));
            var canvas = new SKCanvas(image);
            canvas.Clear(SKColors.Black);

            SKPaint thinLinePaint = new SKPaint
            {
                Style = SKPaintStyle.Stroke,
                Color = SKColors.Red,
                StrokeWidth = 1
            };
            canvas.DrawLine(0, 0, 100, 0, thinLinePaint);

            canvas.Flush();
            using (var save = SKImage.FromBitmap(image))
            using (var data = save.Encode(SKEncodedImageFormat.Png, 100))
            {
                // save the data to a stream
                using (var stream = File.OpenWrite("testSkia0.png"))
                {
                    data.SaveTo(stream);
                }
            }
```

![testSkia0](https://user-images.githubusercontent.com/1452968/75151533-a24b4c80-5752-11ea-8911-48efa188f49e.png)

**Comment by JimBobSquarePants** [comment]
There's a potential fix to this but I will need your advice @tocsoft as I don't know whether this is correct.

The issue looks to me like a rounding error. We lose information when a line is only 1px thick so everything is offset when Clipper does it's thing.

https://github.com/SixLabors/ImageSharp.Drawing/blob/92098af01c0d51476c3891143cb35d378a747753/src/ImageSharp.Drawing/Shapes/Outliner.cs#L222

Adding the following code to the method before scaling fixes this particular issue. The line is placed correctly and is 1px thick.

``` c#
    if (width <= 1F)
    {
         width += .5F;
    }
```
![test](https://user-images.githubusercontent.com/385879/85626121-71c5e180-b664-11ea-9c54-69b30e26d8da.png)

However, we now have a difference of about 0.3% - 1.6% in fine pen writing with 3 failing tests. The stroke width appears to be the same but the antialiasing is heavier. 

**Pre**
![FontShapesAreRenderedCorrectlyWithAPen_Solid900x150_(255,255,255,255)_pen_OpenSans-Regular ttf-50-Sphi-(0,0)](https://user-images.githubusercontent.com/385879/85627482-7be8df80-b666-11ea-95c8-730355609fc3.png)

**Post**
![FontShapesAreRenderedCorrectlyWithAPen_Solid900x150_(255,255,255,255)_pen_OpenSans-Regular ttf-50-Sphi-(0,0)](https://user-images.githubusercontent.com/385879/85627496-80ad9380-b666-11ea-9a5c-25e62a5a1a78.png)

**Pre**
![FontShapesAreRenderedCorrectlyWithAPen_Solid1100x200_(255,255,255,255)_pen_OpenSans-Regular ttf-50-Sphi-(150,50)](https://user-images.githubusercontent.com/385879/85628627-5957c600-b668-11ea-922c-2cbf63fee019.png)

**Post**
![FontShapesAreRenderedCorrectlyWithAPen_Solid1100x200_(255,255,255,255)_pen_OpenSans-Regular ttf-50-Sphi-(150,50)](https://user-images.githubusercontent.com/385879/85628637-5d83e380-b668-11ea-9d2f-9c5a0d9ea9e3.png)

**Pre**
![FontShapesAreRenderedCorrectlyWithAPen_Solid200x150_(255,255,255,255)_pen_SixLaborsSampleAB woff-50-ABAB-(0,0)](https://user-images.githubusercontent.com/385879/85628317-db93ba80-b667-11ea-94fb-45de83e95d7d.png)

**Post**
![FontShapesAreRenderedCorrectlyWithAPen_Solid200x150_(255,255,255,255)_pen_SixLaborsSampleAB woff-50-ABAB-(0,0)](https://user-images.githubusercontent.com/385879/85628334-e1899b80-b667-11ea-844d-fc7e7da5a1ec.png)

**Comment by JimBobSquarePants** [comment]
Looks like my fix is definitely bad. Here's System.Drawing

![text-test](https://user-images.githubusercontent.com/385879/85693698-60192400-b6ce-11ea-80a4-b1ccbf7f4e3a.png)

**Comment by tocsoft** [comment]
I plan to try to take a look over this issue this weekend, I think I need to create some comparisons with of other libs and see where we differ and how.
