### ISSUE TITLE
DrawText() throws 'System.TypeLoadException'

### ISSUE THREAD

**Issue by enriko-riba** [SixLabors/ImageSharp.Drawing#280]
### Description
After upgrading Fonts from 1.0.0-beta19  to 1.0.0 the DrawText extension throws 'System.TypeLoadException' with message:
`"Method 'BeginGlyph' in type 'CachingGlyphRenderer' from assembly 'SixLabors.ImageSharp.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13' does not have an implementation."`

StackTrace:  "   at SixLabors.ImageSharp.Drawing.Processing.Processors.Text.DrawTextProcessor`1.BeforeImageApply() in _/src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor{TPixel}.cs:line 48"

### Steps to Reproduce
1. Create an image: `var image = new Image<Rgba32>(sizeW, sizeH);`
2. Create Font: `var font = SystemFonts.CreateFont("Segoe UI", size, FontStyle.Regular);`
3. Mutate Image with `image.Mutate(ctx => ctx.DrawText(text, font, Color.Blue, position));`

### System Configuration
**SixLabors packages used:**
   SixLabors.Fonts Version="1.0.0" 
   SixLabors.ImageSharp Version="3.0.1"
  SixLabors.ImageSharp.Drawing Version="1.0.0-beta15"

**Other packages:**
    OpenTK Version="4.8.0"   
    StbImageSharp Version="2.27.13" 

**.Net Framework:**  7.0

**OS:** Windows 11

**Comment by JimBobSquarePants** [comment]
Yeah, I haven’t released a build on NuGet targeting it yet. Hoping for a v1 official very soon (1 weekish) but in the interim the nightlies (see readme) will work.

**Comment by JimBobSquarePants** [comment]
v1 has been released now.

**Comment by DHclly** [comment]
thanks，I also encountered this problem
