### ISSUE TITLE
Drawing text fails if x-coordinate is around -1*fontSize

### ISSUE THREAD

**Issue by atruskie** [SixLabors/ImageSharp.Drawing#30]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When drawing text that has a negative x-coordinate an `System.ArgumentOutOfRangeException` exception is thrown.

Traits:
- the bug occurs only when the x-coordinate is
    - negative
   - greater than or around the font size as negative x coordinates (e.g. font size 8, xoffset -8 works, but -9 fails)
- happens irrespective of y-coordinate
- happens with different fonts and font sizes, but varies behaviour subtly

### Steps to Reproduce

The simplest test case:
```
                var image = new Image<Rgb24>(100, 20);
                var text = "2016-12-10";
                var font = SystemFonts.CreateFont("Arial", 10);
                var location = new PointF(-10, 0);

                image.Mutate(x => { x.DrawText(text, font, Color.White, location); });
```
Results in:
```
    SixLabors.ImageSharp.ImageProcessingException: An error occurred when processing the image using DrawTextProcessor`1. See the inner exception for more detail. ---> SixLabors.ImageSharp.ImageProcessingException: An error occurred when processing the image using DrawTextProcessor`1. See the inner exception for more detail. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
  Stack Trace: 
    DrawTextProcessor`1.<OnFrameApply>g__Draw|17_0(List`1 operations, IBrush brush, <>c__DisplayClass17_0& )
    DrawTextProcessor`1.OnFrameApply(ImageFrame`1 source)
```
### System Configuration

- ImageSharp.Drawing version: SixLabors.ImageSharp.Drawing 1.0.0-unstable0421
- Other ImageSharp packages and versions: SixLabors.ImageSharp 1.0.0-unstable0702
- Environment (Operating system, version and so on): Win 10, 19564.1000
- .NET Framework version: .NET Core 3.1.200-preview-014977
- Additional information:

I wrote the following program to try and narrow down the cause:

<details><summary>Test case code</summary>

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var sizes = new float[] {8, 9, 10, 11, 12};
            var fonts = new[] {"Tahoma", "Arial", "Courier New"};
            var offsets = new float[] {-7, -8, -9, -10, -11, -12, -13, -100};

            Console.WriteLine($"| font | size | location | status");
            Console.WriteLine($"|------|------|----------|-------");
            foreach (var font in fonts)
            {
                foreach (var size in sizes)
                {

                    foreach (var offset in offsets)
                    {
                        TestCase(size, font, offset);
                    }
                }
            }

            static void TestCase(float size, string fontName, float xOffset)
            {
                var image = new Image<Rgb24>(100, 20);
                var text = "2016-12-10";
                var font = SystemFonts.CreateFont(fontName, size);
                var location = new PointF(xOffset, 0);

                string error = "Success!";
                try
                {
                    image.Mutate(x => { x.DrawText(text, font, Color.White, location); });

                }
                catch (ImageProcessingException ipe)
                {
                    error = (ipe.InnerException as ImageProcessingException).InnerException.Message;
                }


                
                Console.WriteLine($"| {fontName,11} | {size,2} | {location,26} | {error} |");
            }
        }
```
</details>

Which produces:

| font | size | location | status
|------|------|----------|-------
|      Tahoma |  8 |       PointF [ X=-7, Y=0 ] | Success! |
|      Tahoma |  8 |       PointF [ X=-8, Y=0 ] | Success! |
|      Tahoma |  8 |       PointF [ X=-9, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  8 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  8 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  8 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  8 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  8 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  9 |       PointF [ X=-7, Y=0 ] | Success! |
|      Tahoma |  9 |       PointF [ X=-8, Y=0 ] | Success! |
|      Tahoma |  9 |       PointF [ X=-9, Y=0 ] | Success! |
|      Tahoma |  9 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  9 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  9 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  9 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma |  9 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 10 |       PointF [ X=-7, Y=0 ] | Success! |
|      Tahoma | 10 |       PointF [ X=-8, Y=0 ] | Success! |
|      Tahoma | 10 |       PointF [ X=-9, Y=0 ] | Success! |
|      Tahoma | 10 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 10 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 10 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 10 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 10 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 11 |       PointF [ X=-7, Y=0 ] | Success! |
|      Tahoma | 11 |       PointF [ X=-8, Y=0 ] | Success! |
|      Tahoma | 11 |       PointF [ X=-9, Y=0 ] | Success! |
|      Tahoma | 11 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 11 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 11 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 11 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 11 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 12 |       PointF [ X=-7, Y=0 ] | Success! |
|      Tahoma | 12 |       PointF [ X=-8, Y=0 ] | Success! |
|      Tahoma | 12 |       PointF [ X=-9, Y=0 ] | Success! |
|      Tahoma | 12 |      PointF [ X=-10, Y=0 ] | Success! |
|      Tahoma | 12 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 12 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 12 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|      Tahoma | 12 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  8 |       PointF [ X=-7, Y=0 ] | Success! |
|       Arial |  8 |       PointF [ X=-8, Y=0 ] | Success! |
|       Arial |  8 |       PointF [ X=-9, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  8 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  8 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  8 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  8 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  8 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  9 |       PointF [ X=-7, Y=0 ] | Success! |
|       Arial |  9 |       PointF [ X=-8, Y=0 ] | Success! |
|       Arial |  9 |       PointF [ X=-9, Y=0 ] | Success! |
|       Arial |  9 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  9 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  9 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  9 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial |  9 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 10 |       PointF [ X=-7, Y=0 ] | Success! |
|       Arial | 10 |       PointF [ X=-8, Y=0 ] | Success! |
|       Arial | 10 |       PointF [ X=-9, Y=0 ] | Success! |
|       Arial | 10 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 10 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 10 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 10 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 10 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 11 |       PointF [ X=-7, Y=0 ] | Success! |
|       Arial | 11 |       PointF [ X=-8, Y=0 ] | Success! |
|       Arial | 11 |       PointF [ X=-9, Y=0 ] | Success! |
|       Arial | 11 |      PointF [ X=-10, Y=0 ] | Success! |
|       Arial | 11 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 11 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 11 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 11 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 12 |       PointF [ X=-7, Y=0 ] | Success! |
|       Arial | 12 |       PointF [ X=-8, Y=0 ] | Success! |
|       Arial | 12 |       PointF [ X=-9, Y=0 ] | Success! |
|       Arial | 12 |      PointF [ X=-10, Y=0 ] | Success! |
|       Arial | 12 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 12 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 12 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
|       Arial | 12 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  8 |       PointF [ X=-7, Y=0 ] | Success! |
| Courier New |  8 |       PointF [ X=-8, Y=0 ] | Success! |
| Courier New |  8 |       PointF [ X=-9, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  8 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  8 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  8 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  8 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  8 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  9 |       PointF [ X=-7, Y=0 ] | Success! |
| Courier New |  9 |       PointF [ X=-8, Y=0 ] | Success! |
| Courier New |  9 |       PointF [ X=-9, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  9 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  9 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  9 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  9 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New |  9 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 10 |       PointF [ X=-7, Y=0 ] | Success! |
| Courier New | 10 |       PointF [ X=-8, Y=0 ] | Success! |
| Courier New | 10 |       PointF [ X=-9, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 10 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 10 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 10 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 10 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 10 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 11 |       PointF [ X=-7, Y=0 ] | Success! |
| Courier New | 11 |       PointF [ X=-8, Y=0 ] | Success! |
| Courier New | 11 |       PointF [ X=-9, Y=0 ] | Success! |
| Courier New | 11 |      PointF [ X=-10, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 11 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 11 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 11 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 11 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 12 |       PointF [ X=-7, Y=0 ] | Success! |
| Courier New | 12 |       PointF [ X=-8, Y=0 ] | Success! |
| Courier New | 12 |       PointF [ X=-9, Y=0 ] | Success! |
| Courier New | 12 |      PointF [ X=-10, Y=0 ] | Success! |
| Courier New | 12 |      PointF [ X=-11, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 12 |      PointF [ X=-12, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 12 |      PointF [ X=-13, Y=0 ] | Specified argument was out of the range of valid values. |
| Courier New | 12 |     PointF [ X=-100, Y=0 ] | Specified argument was out of the range of valid values. |

**Comment by JimBobSquarePants** [comment]
Thanks for adding such detail @atruskie !!

I created a test case from your reduced sample and it looks like we've fixed this in master. Likely with #60 

We'll ship beta10 very soon containing all relevant fixes.

**Comment by atruskie** [comment]
Awesome - I've got a smoke test that should fail when this is fixed. I'll look forward to testing it.

Thanks 😄
