### ISSUE TITLE
MissingMethodException SixLabors.ImageSharp.Formats.Jpeg.JpegEncoderf

### ISSUE THREAD

**Issue by dxh-sc** [SixLabors/ImageSharp.Drawing#314]
Hi i update SixLabors.ImageSharp.Drawing from 1.0.0 to 2.1.0, i see this error.

### Description

MissingMethodException: Method not found: 'Void SixLabors.ImageSharp.Formats.Jpeg.JpegEncoder.set_Quality(System.Nullable`1<Int32>)'.

- SixLabors.ImageSharp.Drawing version: 2.1.0

**Comment by JimBobSquarePants** [comment]
Check the transitive version of ImageSharp you have installed.
