### ISSUE TITLE
DrawPolygon with a thickness of less that 0.5 fills produces a filled polygon instead of a outline

### ISSUE THREAD

**Issue by tocsoft** [SixLabors/ImageSharp.Drawing#323]
```c#
  using var image = new Image<Rgba32>(300, 300, Color.White);
  image.Mutate(x => x.DrawPolygon(Color.RebeccaPurple, 0.4f, new PointF[] {
      new(5, 5),
      new(5, 150),
      new(150, 150),
  }));

  image.Save("path.png");
```

issue kicks in on thicknesses less than `0.5f`.

## Expected output
![image](https://github.com/SixLabors/ImageSharp.Drawing/assets/166440/9f27c111-73db-469a-9e34-cb260fe0b554)
## Actual output
![image](https://github.com/SixLabors/ImageSharp.Drawing/assets/166440/8592bca9-964a-4a29-a8d1-e976d5189b5c)

### Discussed in https://github.com/SixLabors/ImageSharp.Drawing/discussions/322

<div type='discussions-op-text'>

<sup>Originally posted by **woutware** March  8, 2024</sup>
Edit: after further investigations this seems to be a bug, I've edited the text below.

When argument thickness is less than 0.5 (e.g. 0.4), method DrawPolygon now fills the polygon, while it used to only stroke the outline, how to get the old behavior? Tested on ImageSharp 3.1.3, ImageSharp.Drawing 2.1.2. When the thickness is equal to 0.5 or greater, the behavior is like it used to be (I think the expected/correct behavior).

I've narrowed it down to the change having happened in ImageSharp.Drawing 2.0.0. It was OK in 1.0.0.

The call that used to not fill the polygon (from DrawPolygonExtensions):

```
 public static IImageProcessingContext DrawPolygon(
     this IImageProcessingContext source,
     Color color,
     float thickness,
     params PointF[] points) =>
     source.DrawPolygon(new SolidBrush(color), thickness, points)
```
</div>

**Comment by tocsoft** [comment]
this is the offending line https://github.com/SixLabors/ImageSharp.Drawing/blob/2a9ee515/src/ImageSharp.Drawing/Shapes/PolygonClipper/PolygonOffsetter.cs#L121 in the third party code

**Comment by woutware** [comment]
I have been searching and testing all afternoon to find out what triggered it, and it triggered between 0.49 and 0.5, so it didn't seem a coincidence. Nice to see I was onto something indeed, it seems a hairy issue.

It would also be nice to have some guidelines for the limitations of the polygon drawing, like until what thickness do you want to quasi guarantee correct output? At some point no output would probably be better than a full fill, e.g. a thickness of 0.001 would be acceptable as not displayed at all in a bitmap.
