### ISSUE TITLE
Exception while drawing text

### ISSUE THREAD

**Issue by arakis** [SixLabors/ImageSharp.Drawing#34]
### Description

I get the following Exeption below.

Code i ran:

```c#
Image.Mutate(ctx => ctx.Fill(Color.Green));
var txt = "FPS: " + Math.Round(RenderApplication.Current.RenderCounter.EventsPerSecond).ToString();
txt += "\nUPS: " + Math.Round(RenderApplication.Current.UpdateCounter.EventsPerSecond).ToString();
Image.Mutate(ctx => ctx.DrawText(txt, DefaultFont, Color.White, new PointF(5, 5)));
```

After multiple of million calls, the exception occured. I was not able to reproduce it! But maybe you have an idea what happend.

The text is writen in the UpdaterThread, but image is readed in a RenderThread. It just juses the `DangerousGetPinnableReferenceToPixelBuffer` and is not modifying any data:

```c#
fixed (void* ptr = &image.DangerousGetPinnableReferenceToPixelBuffer())
{
GL.TexImage2D(
    Target,
    0,
    PixelInternalFormat.Rgba,
    image.Width,
    image.Height,
    0,
    PixelFormat.Rgba,
    PixelType.UnsignedByte,
    (IntPtr)ptr);
}
```

```
Unhandled exception. SixLabors.ImageSharp.ImageProcessingException: An error occurred when processing the image using DrawTextProcessor`1. See the inner exception for more detail.
 ---> SixLabors.ImageSharp.ImageProcessingException: An error occurred when processing the image using DrawTextProcessor`1. See the inner exception for more detail.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at SixLabors.ImageSharp.Processing.SolidBrush.SolidBrushApplicator`1.Apply(Span`1 scanline, Int32 x, Int32 y)
   at SixLabors.ImageSharp.Processing.Processors.Text.DrawTextProcessor`1.<OnFrameApply>g__Draw|17_0(List`1 operations, IBrush brush, <>c__DisplayClass17_0& )
   at SixLabors.ImageSharp.Processing.Processors.Text.DrawTextProcessor`1.OnFrameApply(ImageFrame`1 source)
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.Apply(ImageFrame`1 source)
   --- End of inner exception stack trace ---
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.Apply(ImageFrame`1 source)
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.Apply()
   --- End of inner exception stack trace ---
   at SixLabors.ImageSharp.Processing.Processors.ImageProcessor`1.Apply()
   at SixLabors.ImageSharp.Processing.DefaultImageProcessorContext`1.ApplyProcessor(IImageProcessor processor, Rectangle rectangle)
   at SixLabors.ImageSharp.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextGraphicsOptions options, String text, Font font, IBrush brush, IPen pen, PointF location)
   at SixLabors.ImageSharp.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, TextGraphicsOptions options, String text, Font font, Color color, PointF location)
   at SixLabors.ImageSharp.Processing.DrawTextExtensions.DrawText(IImageProcessingContext source, String text, Font font, Color color, PointF location)
```

### Steps to Reproduce

I was not able to reproduce it. But there was no code change between the runs.

### System Configuration

- ImageSharp.Drawing version: Lastest Nuget
- Linux Gentoo 64 Bit
- .NET Framework version: dotnet Core 3.1

**Comment by arakis** [comment]
It happened again now.

Since I moved from Framework 4.72 to .NET Core 3.1 yesterday, I will try now:
```
ref var b = ref MemoryMarshal.GetReference(image.GetPixelSpan());
SendDataToGPU((IntPtr)Unsafe.AsPointer(ref b));
```

Just a guess: Are the internal allocations threadsafe? So, can multiple Threads create/destroy (seperate images, of course) at the same time?

**Comment by antonfirsov** [comment]
> Are the internal allocations threadsafe? So, can multiple Threads create/destroy (seperate images, of course) at the same time?

Yes, all those internals are supposed to be thread safe. It's unlikely we have a bug in this area.

**Comment by arakis** [comment]
Image Size: 100x100
Font: Dejavu Serif (common on Linux), regular, Size 15
Text:
```
FPS: 60
UPS: <long number, larger than the image width>
```

But beware: This bug occurred only 2x in round about 200 starts. It's a very rare bug.
Generally, i can garantee, that the Reader-Thread (the OpenGL Renderer Routine in this case) do no write. Only the Updater-Thread is writing to the image - without resizing. They can infere (there's no lock), but this should not matter for the reader or writer (Pixles can be overwritten while they are readed). The Reader just takes the pointer, no special other Methods.

Just another guess: Maybe there's a problem in the bound check if you write a quiet large string?

**Comment by arakis** [comment]
I was able to reproduce it. I think my guess was correct, if the string is very large, the exceptions will be thrown every time. I tried to provocate with a larger string as normal (42 in Length), and that's the result:

![image](https://user-images.githubusercontent.com/1831942/78456170-689b2900-76a2-11ea-9363-33958577b356.png)

The String being written:
```
FPS: 3
UPS: 106347106347106347106347106347
```

**Comment by JimBobSquarePants** [comment]
Ah ok, yep that makes sense; we need to determine our preferred behavior then. Throw or Crop. 

In `DrawImage` we only throw if there is no overlap of the target and source image locations. We simply chop off what doesn't fit the bounds of the destination.

**Comment by tocsoft** [comment]
we shouldn't be throwing when a shape/text being drawn extends beyond the visible area of the image/rectangle...we should be just cropping we do do this we just must have an edge case that is hitting the very edge... guessing we have an off by one issue somewhere in the brushes

**Comment by arakis** [comment]
Drawing a text should (by default) always cropped because otherwise the developer has always to check the bound.

In my opinion, a draw should never throw (by default), that's the same behavior as System.Drawing and Cairo (Unix based drawing system). It has good reasons.

**Comment by tocsoft** [comment]
I've just tested this issue against our beta7 release where the issue occurs and again against our latest nightly (myget) where the error no longer presents itself.... in hindsight I vaguely remember fixing an issue like this in the past, looks like I've already fixed this one.

If you can please try against our nightlies if possible that should resolve your issue.
