### ISSUE TITLE
Crashes with huge font size.

### ISSUE THREAD

**Issue by gencuro** [SixLabors/ImageSharp.Drawing#37]
Hello.

Application crashes with font size greater than 35. Code to reproduce:

            using (var image = new Image<Rgba32>(300, 200))
            {
                string text = "TEST text foiw|\\";

                var font = SixLabors.Fonts.SystemFonts.CreateFont("Arial", 40, Fonts.FontStyle.Regular);

                image.Mutate(x => {
                    x.BackgroundColor(Rgba32.White).DrawLines(
                        new GraphicsOptions(false),
                        Rgba32.Black,
                        1,
                        new Primitives.PointF(0, 50),
                        new Primitives.PointF(150, 50));
                    
                    x.DrawText<Rgba32>(new TextGraphicsOptions(false), text, font, Rgba32.Black, new Primitives.PointF(50, 50));
                }
                );
            }

Also I noticed that this reaction on some specific glyph from my test string. Didn't dive dipper. With text "123" everything works fine.

**Comment by JimBobSquarePants** [comment]
@gencuro looks like we've already fixed this in master. We'll be releasing beta 10 soon with all the latest fixes.

``` c#
using (var image = new Image<Rgba32>(300, 200))
{
    string text = "TEST text foiw|\\";

    Fonts.Font font = Fonts.SystemFonts.CreateFont("Arial", 40, Fonts.FontStyle.Regular);
    var graphicsOptions = new GraphicsOptions { Antialias = false };
    image.Mutate(x =>
    {
        x.BackgroundColor(Color.White)
        .DrawLines(
            new ShapeGraphicsOptions { GraphicsOptions = graphicsOptions },
            Color.Black,
            1,
            new PointF(0, 50),
            new PointF(150, 50))
        .DrawText(
            new TextGraphicsOptions { GraphicsOptions = graphicsOptions },
            text,
            font,
            Color.Black,
            new PointF(50, 50));
    });
}
```
