### ISSUE TITLE
Shapes: FeatureRequest - Copy functionality for AddArc on PathBuilder

### ISSUE THREAD

**Issue by Astralking** [SixLabors/ImageSharp.Drawing#4]
### Prequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Recently we've been encountering numerous "Error occured in GDI+" issues and even after attempting to dispose of everything correctly the issue still occurs with no consistency. In case this issue ever started happening all the time live sites we wanted to preemptively use an alternative for our image creation for in ASP.NET (WebAPI + MVC)

All features we use seem to already have been ported over to ImageSharp however currently there seems to be no way of adding an arc to a Path in the same way GraphicsPath works in System.Drawing, preventing any sort of exact logic replacement. I contemplated trying to do something similar with a bezier like in the samples however it seemed overkill.

I imagine it would be integrated into PathBuilder however it will need to be drawn on top of an existing image (which would previously have been in the graphics object). It seems the existing implementation with Polygon simply saves the image off directly however there might be a way to get this working with the existing code base I'm unaware of using "Fill". If an implementation for this does exist please let me know and close this issue.

### Steps to Reproduce

Example System.Drawing code to replicate in code:

```
var locationPoint = new Point(20, 20);
var size = new Size(150, 150);
var arcBounds = new Rectangle(locationPoint, size);

using (var graphics = Graphics.FromImage(pictureBox1.Image))
using (var path = new GraphicsPath())
{
    float startAngle = 45;
    float sweepAngle = 90;

    path.AddArc(arcBounds, startAngle, sweepAngle);
    path.CloseFigure();
    graphics.FillPath(new SolidBrush(Color.Black), path);
    graphics.DrawPath(new Pen(Color.Red), path);
}
```

And resulting picture image:
![IncisionImage](https://image.ibb.co/kwuULH/Capture.jpg)

If you need more information please let me know. Also, thanks for creating this library! It seems Microsoft gave up a long time ago on GDI+ issues.

### System Configuration

- ImageSharp version: v1.0.0-beta0002
- Environment (Operating system, version and so on): Windows Server 2012 R2/Windows 10
- .NET Framework version: 4.6.1

**Comment by JimBobSquarePants** [comment]
I've added the "help wanted" label to this issue as it is a feature I do believe we require but will need assistance in delivering.

**Comment by derBobo** [comment]
I started implementing this feature [here](https://github.com/derBobo/ImageSharp.Drawing). Right now I'm struggeling to implement the Transform Method for the EllipticalArcLineSegment maybe Someone here can have a look and help me.

**Comment by JimBobSquarePants** [comment]
@derBobo That's awesome thanks! If you raise a draft PR against this repository we can all work together to get it completed.

**Comment by derBobo** [comment]
I'll do that later this week, first I have to finish some stuff for my work. Am 14.06.2021 16:04 schrieb James Jackson-South ***@***.***>:
@derBobo That's awesome thanks! If you raise a draft PR against this repository we can all work together to get it completed.

**Comment by antonfirsov** [comment]
Triaging to RC1 now since we hoping in community help, we can push it out later, if we see that we can't make it.

**Comment by derBobo** [comment]
The pr #144 is merged now, so this issue can be closed.

**Comment by JimBobSquarePants** [comment]
Thanks @derBobo !!
