### ISSUE TITLE
NuGet package incompatible with 1.0.0-rc0001 release of ImageSharp

### ISSUE THREAD

**Issue by n8allan** [SixLabors/ImageSharp.Drawing#44]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using the latest nuget packages (`v1.0.0-beta0007` for `ImageSharp.Drawing` and `v1.0.0-rc0001` for `ImageSharp`) I get errors such as:
`error CS0012: The type 'IImageProcessingContext' is defined in an assembly that is not referenced. You must add a reference to assembly 'SixLabors.ImageSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.` when compiling.

Tracking it down, it appears that `ImageSharp.Drawing` references `ImageSharp` with no `publickeytoken`, whereas the rc release now has a `publickeytoken`.

I think all that is needed is a new build and package for ImageSharp.Drawing and the compiler will be happy.

### Steps to Reproduce
1. Create a new project and add the following nuget packages: `v1.0.0-beta0007 for ImageSharp.Drawing` and `v1.0.0-rc0001 for ImageSharp`
2. Make use of a feature in ImageSharp.Drawing in the code.
3. Attempt to compile.

### System Configuration
.NET Standard 2.1

- ImageSharp.Drawing version: v1.0.0-beta0007
- Other ImageSharp packages and versions: ImageSharp v1.0.0-rc0001
- Environment (Operating system, version and so on): Windows 10 Pro
- .NET Framework version: .NET Standard 2.1
- Additional information:

**Comment by James-Jackson-South** [comment]
Thanks @n8allan 

There are compatible builds on MyGet but we should release a new beta to Nuget to make it easier for consumers. 

@tocsoft other than the basics, is there any reason you think we couldn't publish a new beta?

**Comment by tocsoft** [comment]
going to start pulling an updated beta together today

**Comment by tocsoft** [comment]
SixLabors.ImageSharp.Drawing 1.0.0-beta0008 has been released that's compatible with  the imagesharp 1.0.0-rc0001 release.
