### ISSUE TITLE
Shapes: Accessors for Line segments.

### ISSUE THREAD

**Issue by xclud** [SixLabors/ImageSharp.Drawing#6]
Looking at the source code i see there is not property to get `Start` of a `LinearLineSegment `as well as `ControlPoints` of a `CubicBezierLineSegment`.

I am doing a project and i need to load a font (using SixLabors.Fonts) and getting access to each glyph's segments.

Currently i am getting value of these private fields using Reflection, but i believe it would be a great enhancement if those properties are public.

**Comment by antonfirsov** [comment]
From what I see, `LinearLineSegment` has `.Flatten()` to get the points, and `CubicBezierLineSegment` has public has a public `ControlPoints` property.

Closing this for now, feel free to reopen, if I'm misunderstanding something.
