### ISSUE TITLE
Exception when drawing rectangle outside image area

### ISSUE THREAD

**Issue by pekspro** [SixLabors/ImageSharp.Drawing#65]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp.Drawing
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp.Drawing/issues) and [closed](https://github.com/SixLabors/ImageSharp.Drawing/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Drawing a rectangle outside the image area throws an exception with the message:

    Parameter "rectangle.Width" (System.Int32) must be greater than 0, was 0 (Parameter 'rectangle.Width')

### Steps to Reproduce
This function throws the exception if x <= -100 or x >= 100.

	void Test(int xpos)
	{
	    int width = 100;
	    int height = 100;
	
	    using (var image = new Image<Rgba32>(width, height, Rgba32.ParseHex("EEEEEE")))
	    {
	        //int xpos = -100; //Crash
	        //int xpos = -99; //Fine
	        //int xpos = 99; // Fine
	        //int xpos = 100; //Crash
	
	        Rectangle rectangle = new Rectangle(xpos, 0, width, height);
	
	        image.Mutate(x => x.Fill(Color.Black, rectangle));
	    }
	}
		
### System Configuration

- ImageSharp.Drawing version: 1.0.0-rc0003

**Comment by tocsoft** [comment]
@pekspro we don't have an  1.0.0-rc0003 version of `ImageSharp.Drawing`  as its still in beta can you please confirm the version of  the drawing package please

**Comment by pekspro** [comment]
Ups, sorry about that @tocsoft . I am using:

SixLabors.ImageSharp - 1.0.0-rc0003
SixLabors.ImageSharp.Drawing - 1.0.0-beta0010
