### ISSUE TITLE
Shapes: Add Scan() API to IPath

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp.Drawing#7]
Currently region scanning implemented within `ImageSharp.Drawing` is based on `IPath.FindIntersections()`.
Calculating generic `segment x segment` intersections is unnecessary and sub-optimal in this use case.

To enable all optimizations possible in this context:
- We should define a `Scan(...)` API right on the surface of `IPath`
- Consider defining it as a multi-line scanning

**Comment by JimBobSquarePants** [comment]
This paper on Scanline edge-flag algorithm for antialiasing looks relevant and interesting (_I think_)

http://mlab.uiah.fi/~kkallio/antialiasing/

**Comment by antonfirsov** [comment]
Closing this in favor of #90
