### ISSUE TITLE
Review and fix parameter names and XML docs in extension methods

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp.Drawing#94]
There are many leftovers from the time when extension methods used to operate on an image:

https://github.com/SixLabors/ImageSharp.Drawing/blob/799d6afce0749f3316f6e766ac8884cccc9ef46b/src/ImageSharp.Drawing/Processing/Extensions/DrawLineExtensions.cs#L95-L100

**Comment by antonfirsov** [comment]
I believe it would be better to address this in RC1.

**Comment by JimBobSquarePants** [comment]
Agreed

**Comment by JimBobSquarePants** [comment]
I've been reading through the docs and it looks like I've fixed all the issues over time in other PRs. I'm going to close this as it's looking good.

**Comment by antonfirsov** [comment]
This is not true:

https://github.com/SixLabors/ImageSharp.Drawing/blob/b059f3142106b9bf12922acd5f25156a41cc1fe6/src/ImageSharp.Drawing/Processing/Extensions/DrawBezierExtensions.cs#L76-L82

An easy way to address this would be to run a find & replace for `The image this method extends`.
